### ISSUE TITLE
Multiple videos for one exercise

### ISSUE THREAD

**Issue by MichielBoone** [sprenge/kineperfect#5]
When showing a squat we’ll have multiple variations of this exercise. Is it possible to integrate multiple videos for one exercise.
Ex: squat: air squat, goblet squat, overhead squat. Pistol squat, skater squat, barbelle squat

**Comment by sprenge** [comment]
Would like to understand first the impact on the workout.  Do we want to assign one workout per variant or is it one workout containing all variants ? We could also add a field in the exercise table that refers to a "root" exercise because they all share the same description.

**Comment by sprenge** [comment]
As far as I understood, the request was a search function in the coach exercises.  Implemented in v.0.01

**Comment by sprenge** [comment]
available
